export const projects = [
  {
    id: 1,
    title: "Shop Smarter with QuickBasket",
    description: "Experience premium mobile shopping with instant delivery and trusted service. Join thousands enjoying fast, smart, and secure online shopping.",
    image: "/projects/quickbasket.png",
    tags: [],
    link: "https://www.quickbasket.com.ng/",
  },
  {
    id: 2,
    title: "STIH Institute",
    description: "An educational platform designed for professional certification and career growth tracking.",
    image: "/projects/stih.png",
    tags: [],
    link: "https://stiheinstitute.com/",
  },
  {
    id: 3,
    title: "Flybird FE",
    description: "Modern frontend architecture for a high-traffic logistics and travel management system.",
    image: "/projects/flybird.png",
    tags: [],
    link: "https://flybird-fe.vercel.app/",
  },
  {
    id: 4,
    title: "Nigeria's Automotive Marketplace for Cars",
    description: "Connect with thousands of buyers and sellers in Nigeria’s most trusted automotive ecosystem.",
    image: "/projects/c9x.png",
    tags: [],
    link: "https://c9x.thec9group.com/",
  },
  {
    id: 5,
    title: "Enabling Everyone to Own a Future",
    description: "Find impactful ventures and transparent investments created for those who believe prosperity is a shared journey.",
    image: "/projects/qompas.png",
    tags: [],
    link: "https://qompas-app.vercel.app/",
  },
  {
    id: 6,
    title: "Premium Paint That Lasts 2X Longer Than Ordinary Brands",
    description: "Fade-resistant technology stays vibrant for years. One-coat coverage saves time and money. Eco-friendly formula, safe for families.",
    image: "/projects/nexgen.png",
    tags: [],
    link: "https://www.nexgenpaint.com/",
  },
  {
    id: 7,
    title: "Skillahead",
    description: "EdTech platform empowering African talent with market-ready digital skills and placement.",
    image: "/projects/skillahead.png",
    tags: [],
    link: "https://skillahead.vercel.app/",
  },
  {
    id: 8,
    title: "Rokswood",
    description: "Corporate platform for a leading real estate and property development firm.",
    image: "/projects/rokswood.png",
    tags: [],
    link: "https://www.rokswood.com/",
  },
  {
    id: 9,
    title: "Rokswood Energy",
    description: "Energy management system for monitoring and optimizing power distribution in smart communities.",
    image: "/projects/rokswoodenergy.png",
    tags: [],
    link: "https://www.rokswoodenergy.com/",
  },
];


